#ifndef BOLT_S3_CLIENT_MODEL_H
#define BOLT_S3_CLIENT_MODEL_H

#include <aws/s3/S3ServiceClientModel.h>

#include <functional>
#include <future>

namespace ProjectN {
namespace Bolt {

class BoltS3Client;

/* Service model async handlers definitions */
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::AbortMultipartUploadRequest&, const Aws::S3::Model::AbortMultipartUploadOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> AbortMultipartUploadResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::CompleteMultipartUploadRequest&, const Aws::S3::Model::CompleteMultipartUploadOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> CompleteMultipartUploadResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::CopyObjectRequest&, const Aws::S3::Model::CopyObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> CopyObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::CreateBucketRequest&, const Aws::S3::Model::CreateBucketOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> CreateBucketResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::CreateMultipartUploadRequest&, const Aws::S3::Model::CreateMultipartUploadOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> CreateMultipartUploadResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketRequest&, const Aws::S3::Model::DeleteBucketOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketAnalyticsConfigurationRequest&, const Aws::S3::Model::DeleteBucketAnalyticsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketAnalyticsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketCorsRequest&, const Aws::S3::Model::DeleteBucketCorsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketCorsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketEncryptionRequest&, const Aws::S3::Model::DeleteBucketEncryptionOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketEncryptionResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketIntelligentTieringConfigurationRequest&, const Aws::S3::Model::DeleteBucketIntelligentTieringConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketIntelligentTieringConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketInventoryConfigurationRequest&, const Aws::S3::Model::DeleteBucketInventoryConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketInventoryConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketLifecycleRequest&, const Aws::S3::Model::DeleteBucketLifecycleOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketLifecycleResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketMetricsConfigurationRequest&, const Aws::S3::Model::DeleteBucketMetricsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketMetricsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketOwnershipControlsRequest&, const Aws::S3::Model::DeleteBucketOwnershipControlsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketOwnershipControlsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketPolicyRequest&, const Aws::S3::Model::DeleteBucketPolicyOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketPolicyResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketReplicationRequest&, const Aws::S3::Model::DeleteBucketReplicationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketReplicationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketTaggingRequest&, const Aws::S3::Model::DeleteBucketTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteBucketWebsiteRequest&, const Aws::S3::Model::DeleteBucketWebsiteOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteBucketWebsiteResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteObjectRequest&, const Aws::S3::Model::DeleteObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteObjectTaggingRequest&, const Aws::S3::Model::DeleteObjectTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteObjectTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeleteObjectsRequest&, const Aws::S3::Model::DeleteObjectsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeleteObjectsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::DeletePublicAccessBlockRequest&, const Aws::S3::Model::DeletePublicAccessBlockOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> DeletePublicAccessBlockResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketAccelerateConfigurationRequest&, const Aws::S3::Model::GetBucketAccelerateConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketAccelerateConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketAclRequest&, const Aws::S3::Model::GetBucketAclOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketAclResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketAnalyticsConfigurationRequest&, const Aws::S3::Model::GetBucketAnalyticsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketAnalyticsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketCorsRequest&, const Aws::S3::Model::GetBucketCorsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketCorsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketEncryptionRequest&, const Aws::S3::Model::GetBucketEncryptionOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketEncryptionResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketIntelligentTieringConfigurationRequest&, const Aws::S3::Model::GetBucketIntelligentTieringConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketIntelligentTieringConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketInventoryConfigurationRequest&, const Aws::S3::Model::GetBucketInventoryConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketInventoryConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketLifecycleConfigurationRequest&, const Aws::S3::Model::GetBucketLifecycleConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketLifecycleConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketLocationRequest&, const Aws::S3::Model::GetBucketLocationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketLocationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketLoggingRequest&, const Aws::S3::Model::GetBucketLoggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketLoggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketMetricsConfigurationRequest&, const Aws::S3::Model::GetBucketMetricsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketMetricsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketNotificationConfigurationRequest&, const Aws::S3::Model::GetBucketNotificationConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketNotificationConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketOwnershipControlsRequest&, const Aws::S3::Model::GetBucketOwnershipControlsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketOwnershipControlsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketPolicyRequest&, Aws::S3::Model::GetBucketPolicyOutcome, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketPolicyResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketPolicyStatusRequest&, const Aws::S3::Model::GetBucketPolicyStatusOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketPolicyStatusResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketReplicationRequest&, const Aws::S3::Model::GetBucketReplicationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketReplicationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketRequestPaymentRequest&, const Aws::S3::Model::GetBucketRequestPaymentOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketRequestPaymentResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketTaggingRequest&, const Aws::S3::Model::GetBucketTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketVersioningRequest&, const Aws::S3::Model::GetBucketVersioningOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketVersioningResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetBucketWebsiteRequest&, const Aws::S3::Model::GetBucketWebsiteOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetBucketWebsiteResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectRequest&, Aws::S3::Model::GetObjectOutcome, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectAclRequest&, const Aws::S3::Model::GetObjectAclOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectAclResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectAttributesRequest&, const Aws::S3::Model::GetObjectAttributesOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectAttributesResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectLegalHoldRequest&, const Aws::S3::Model::GetObjectLegalHoldOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectLegalHoldResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectLockConfigurationRequest&, const Aws::S3::Model::GetObjectLockConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectLockConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectRetentionRequest&, const Aws::S3::Model::GetObjectRetentionOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectRetentionResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectTaggingRequest&, const Aws::S3::Model::GetObjectTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetObjectTorrentRequest&, Aws::S3::Model::GetObjectTorrentOutcome, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetObjectTorrentResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::GetPublicAccessBlockRequest&, const Aws::S3::Model::GetPublicAccessBlockOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> GetPublicAccessBlockResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::HeadBucketRequest&, const Aws::S3::Model::HeadBucketOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> HeadBucketResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::HeadObjectRequest&, const Aws::S3::Model::HeadObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> HeadObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListBucketAnalyticsConfigurationsRequest&, const Aws::S3::Model::ListBucketAnalyticsConfigurationsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListBucketAnalyticsConfigurationsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListBucketIntelligentTieringConfigurationsRequest&, const Aws::S3::Model::ListBucketIntelligentTieringConfigurationsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListBucketIntelligentTieringConfigurationsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListBucketInventoryConfigurationsRequest&, const Aws::S3::Model::ListBucketInventoryConfigurationsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListBucketInventoryConfigurationsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListBucketMetricsConfigurationsRequest&, const Aws::S3::Model::ListBucketMetricsConfigurationsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListBucketMetricsConfigurationsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListBucketsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListBucketsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListMultipartUploadsRequest&, const Aws::S3::Model::ListMultipartUploadsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListMultipartUploadsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListObjectVersionsRequest&, const Aws::S3::Model::ListObjectVersionsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListObjectVersionsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListObjectsRequest&, const Aws::S3::Model::ListObjectsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListObjectsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListObjectsV2Request&, const Aws::S3::Model::ListObjectsV2Outcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListObjectsV2ResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::ListPartsRequest&, const Aws::S3::Model::ListPartsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> ListPartsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketAccelerateConfigurationRequest&, const Aws::S3::Model::PutBucketAccelerateConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketAccelerateConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketAclRequest&, const Aws::S3::Model::PutBucketAclOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketAclResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketAnalyticsConfigurationRequest&, const Aws::S3::Model::PutBucketAnalyticsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketAnalyticsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketCorsRequest&, const Aws::S3::Model::PutBucketCorsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketCorsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketEncryptionRequest&, const Aws::S3::Model::PutBucketEncryptionOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketEncryptionResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketIntelligentTieringConfigurationRequest&, const Aws::S3::Model::PutBucketIntelligentTieringConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketIntelligentTieringConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketInventoryConfigurationRequest&, const Aws::S3::Model::PutBucketInventoryConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketInventoryConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketLifecycleConfigurationRequest&, const Aws::S3::Model::PutBucketLifecycleConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketLifecycleConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketLoggingRequest&, const Aws::S3::Model::PutBucketLoggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketLoggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketMetricsConfigurationRequest&, const Aws::S3::Model::PutBucketMetricsConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketMetricsConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketNotificationConfigurationRequest&, const Aws::S3::Model::PutBucketNotificationConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketNotificationConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketOwnershipControlsRequest&, const Aws::S3::Model::PutBucketOwnershipControlsOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketOwnershipControlsResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketPolicyRequest&, const Aws::S3::Model::PutBucketPolicyOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketPolicyResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketReplicationRequest&, const Aws::S3::Model::PutBucketReplicationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketReplicationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketRequestPaymentRequest&, const Aws::S3::Model::PutBucketRequestPaymentOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketRequestPaymentResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketTaggingRequest&, const Aws::S3::Model::PutBucketTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketVersioningRequest&, const Aws::S3::Model::PutBucketVersioningOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketVersioningResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutBucketWebsiteRequest&, const Aws::S3::Model::PutBucketWebsiteOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutBucketWebsiteResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectRequest&, const Aws::S3::Model::PutObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectAclRequest&, const Aws::S3::Model::PutObjectAclOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectAclResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectLegalHoldRequest&, const Aws::S3::Model::PutObjectLegalHoldOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectLegalHoldResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectLockConfigurationRequest&, const Aws::S3::Model::PutObjectLockConfigurationOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectLockConfigurationResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectRetentionRequest&, const Aws::S3::Model::PutObjectRetentionOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectRetentionResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutObjectTaggingRequest&, const Aws::S3::Model::PutObjectTaggingOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutObjectTaggingResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::PutPublicAccessBlockRequest&, const Aws::S3::Model::PutPublicAccessBlockOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> PutPublicAccessBlockResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::RestoreObjectRequest&, const Aws::S3::Model::RestoreObjectOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> RestoreObjectResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::SelectObjectContentRequest&, const Aws::S3::Model::SelectObjectContentOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> SelectObjectContentResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::UploadPartRequest&, const Aws::S3::Model::UploadPartOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> UploadPartResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::UploadPartCopyRequest&, const Aws::S3::Model::UploadPartCopyOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> UploadPartCopyResponseReceivedHandler;
typedef std::function<void(const BoltS3Client*, const Aws::S3::Model::WriteGetObjectResponseRequest&, const Aws::S3::Model::WriteGetObjectResponseOutcome&, const std::shared_ptr<const Aws::Client::AsyncCallerContext>&)> WriteGetObjectResponseResponseReceivedHandler;
/* End of service model async handlers definitions */
}  // namespace Bolt
}  // namespace ProjectN

#endif  // BOLT_S3_CLIENT_MODEL_H