if(CMAKE_HOST_WIN32)
    set(PLATFORM_WINDOWS 1)
elseif(CMAKE_HOST_APPLE)
    set(PLATFORM_APPLE 1)
elseif(CMAKE_HOST_UNIX)
    set(PLATFORM_LINUX 1)
else()
    message(FATAL_ERROR "Unknown host OS; unable to determine platform compilation target")
endif()
