name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        include:
          # - os: windows-latest
            # vcpkgCommitId: '${{ env.VCPKG_COMMIT_ID }}'
          - os: ubuntu-latest
            aws-sdk-commit-hash: f14984af3738e69f197bf0e647a8dca12de92996
          # - os: macos-latest
            # vcpkgCommitId: ''${{ env.VCPKG_COMMIT_ID }}'

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/aws-sdk-cpp.yml
        with: 
          aws-sdk-commit-hash: '${{ matrix.aws-sdk-commit-hash }}'

      # - name: Configure CMake
      #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

      # - name: Build
      #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}