name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        include:
          # - os: windows-latest
            # vcpkgCommitId: '${{ env.VCPKG_COMMIT_ID }}'
          - os: ubuntu-latest
            aws-sdk-commit-hash: f14984af3738e69f197bf0e647a8dca12de92996
          # - os: macos-latest
            # vcpkgCommitId: ''${{ env.VCPKG_COMMIT_ID }}'


    steps:
      - name: Linux apt-get
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev

      - name: git checkout aws sdk
        run: |
          git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
          cd ./aws-sdk-cpp && git checkout  ${{ matrix.aws-sdk-commit-hash }}

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{github.workspace}}/sdk_build
          key: ${{ runner.os }}-aws-sdk-cpp-commit-${{ matrix.aws-sdk-commit-hash}}

      - name: Checkout and build aws-sdk-cpp
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp
          cd ${{github.workspace}}/aws-sdk-cpp && git checkout  ${{ matrix.aws-sdk-commit-hash }}
          mkdir ${{github.workspace}}/sdk_build
          cd ${{github.workspace}}/sdk_build
          cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="s3"
          make

      - name: Build and install aws-sdk-cpp
        run: |
          cd ${{github.workspace}}/sdk_build
          make install

      - uses: actions/cache/save@v3
        id: cache-save
        with:
          path: ${{github.workspace}}/sdk_build
          key: ${{ runner.os }}-aws-sdk-cpp-commit-${{ matrix.aws-sdk-commit-hash}}

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      # - name: Configure CMake
      #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

      # - name: Build
      #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}