name: Release
on:
  workflow_dispatch:

jobs:
  release-build:
    uses: ./.github/workflows/build.yml
  create-release:
    needs: release-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3

    - name: Get tag version
      run: echo VERSION=`awk '/OWN_VERSION/ {$2; sub(/\)$/, "", $2); print $2; exit}' CMakeLists.txt` >> $GITHUB_ENV 

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.VERSION }}
        artifacts: ${{github.workspace}}/artifact/*.zip
        allowUpdates: true
        commit: ${{ $GITHUB_SHA }}


      
