name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  release-build:
    uses: ./.github/workflows/build.yml
  create-release:
    needs: release-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3

    - name: Display structure of downloaded files
      run: ls -R

    # - uses: ncipollo/release-action@v1
    #   with:
    #     tag: ${{ input.version }}
    #     artifacts: ${{github.workspace}}/artifacts/*.zip


      
